### PR TITLE
Generate a file header record

### PR DESCRIPTION
**Pull request by tetiana12345678**
## Specification

screen shot 2018-02-28 at 5 34 48 pm

- [x] Record Type Code

| Field                       |                1 |
|-----------------------------|------------------|
| Data Element Name           | Record Type Code |
| Field Inclusion Requirement |                M |
| Contents                    |              '5' |
| Length                      |                1 |
| Position                    |            01-01 |

The code identifying the File Header Record is 1.

- [x] Priority Code

| Field                       |            2 |
|-----------------------------|--------------|
| Data Element Name           | Prioriy Code |
| Field Inclusion Requirement |            R |
| Contents                    |         '01' |
| Length                      |            2 |
| Position                    |        02-03 |

The lower the number, the higher processing priority. Currently,
only 01 is used.

- [x] Immediate Destination

| Field                       |                     3 |
|-----------------------------|-----------------------|
| Data Element Name           | Immediate Destination |
| Field Inclusion Requirement |                     M |
| Contents                    |            b071000505 |
| Length                      |                    10 |
| Position                    |                 04-13 |

LaSalle Bank N.A. or Standard Federal Bank’s transit routing
number preceded by a blank. (071000505 for LaSalle and
072000805 for Standard Federal)

- [x] Immediate Origin

| Field                       |                4 |
|-----------------------------|------------------|
| Data Element Name           | Immediate Origin |
| Field Inclusion Requirement |                M |
| Contents                    |       NNNNNNNNNN |
| Length                      |               10 |
| Position                    |            14-23 |

Your 10-digit company number. The use of an IRS Federal Tax
Identification Number as a company identification is
recommended. Otherwise, ABN AMRO will create a unique
number for your company

- [x] File Creation Date

| Field                       |                  5 |
|-----------------------------|--------------------|
| Data Element Name           | File Creation Date |
| Field Inclusion Requirement |                  M |
| Contents                    |             YYMMDD |
| Length                      |                  6 |
| Position                    |              24-29 |

- [x] File Creation Time

| Field                       |                  6 |
|-----------------------------|--------------------|
| Data Element Name           | File Creation Time |
| Field Inclusion Requirement |                  O |
| Contents                    |               HHMM |
| Length                      |                  4 |
| Position                    |              30-33 |

- [x] File ID Modifier

| Field                       |                             7 |
|-----------------------------|-------------------------------|
| Data Element Name           |              File ID Modifier |
| Field Inclusion Requirement |                             M |
| Contents                    | Upper Case A-Z - Numeric 0-9 |
| Length                      |                             1 |
| Position                    |                         34-34 |

Code to distinguish among multiple input files. Label the first
(or only) file “A”, and continue in sequence (A-Z). If more than
one file is delivered, they must have different modifiers.

- [x] Record Size

| Field                       |           8 |
|-----------------------------|-------------|
| Data Element Name           | Record Size |
| Field Inclusion Requirement |           M |
| Contents                    |       '094' |
| Length                      |           3 |
| Position                    |       35-37 |

Number of bytes per record. Enter ‘094.’

- [x] Blocking Factor

| Field                       |               9 |
|-----------------------------|-----------------|
| Data Element Name           | Blocking Factor |
| Field Inclusion Requirement |               M |
| Contents                    |            '10' |
| Length                      |               2 |
| Position                    |           38-39 |

Block at 10.

- [x] Format Code

| Field                       |           10 |
|-----------------------------|-------------|
| Data Element Name           | Format Code |
| Field Inclusion Requirement |           M |
| Contents                    |         '1' |
| Length                      |           1 |
| Position                    |       40-40 |

Currently there is only one code. Enter 1.

- [x] Immediate Destination Name

| Field                       |                          11 |
|-----------------------------|----------------------------|
| Data Element Name           | Immediate Destination Name |
| Field Inclusion Requirement |                          O |
| Contents                    |           LaSalle Bank N.A |
| Length                      |                         23 |
| Position                    |                      41-63 |
|                             |                            |

Enter LaSalle Bank or Standard Federal Bank

- [x] Immediate Origin Name

| Field                       |                    12 |
|-----------------------------|-----------------------|
| Data Element Name           | Immediate Origin Name |
| Field Inclusion Requirement |                     O |
| Contents                    |           Hollar Inc. |
| Length                      |                    23 |
| Position                    |                 64-86 |
|                             |                       |

Your company’s name, up to 23 characters.

- [x] Reference Code

| Field                       |             13 |
|-----------------------------|----------------|
| Data Element Name           | Reference Code |
| Field Inclusion Requirement |              M |
| Contents                    |   AlphaNumeric |
| Length                      |              8 |
| Position                    |          87-94 |

Optional field you may use to describe input file for internal accounting purposes.

### CODE REVIEW

**Comment by tetiana12345678** [comment]
- [x] Add field validation (check for required fields to have correct value) 
- [x] Add README to describe API
- [x] Add specs, docs and moduledocs
- [x] Add format and length validation where applicable

Shall we add dialyzer to keep an eye on our specs?

**Comment by tetiana12345678** [comment]
Shall time `creation date` and `time creation time` be passed in params? It make sense to generate those values when file got created, rather then rely and validate user input. Thoughts?

**Comment by tetiana12345678** [comment]
**NOTE** Opened against `chore/setup_circle_ci` branch.

**Review by nicholasjhenry — COMMENTED** [review]
Let's discuss the API before forward, here are a couple of takes on it. It would be nice to make this easy to use, removing the archaic details of working with ACH. Thoughts? (probably best to discuss in person)

## take one

create new ach file struct:
```elixir
iex> ach = ExAch.new()
%ExAch.Ach{}
```

add file header:
```elixir
iex> 

destination = %{
  routing_number: "b071000505",
  bank_name: "RBC ROYAL Bank",
}

origin = %{
  routing_number: "0123456789",
  bank_name: "ORIGIN Bank"
}

file = %{
  created_at: ~N[18-04-2015 12:05],
  id_modifier: 1,
}
     
iex> ExAch.put_file_header(achd, "refcode", origin, destination, file)
{:ok, %ExAch.Ach{file_header: %ExAch.FileHeader{blocking_factor: %ExAch.Field{...}, ...}}}
```

## take two

create new ach file struct:
```elixir
ExAch.new("refcode")
|> ExAch.put_file_metadata(1, ~N[18-04-2015 12:05])
|> ExAch.put_origin("0123456789", "ORIGIN Bank")
|> ExAch.put_destination("b071000505", "RBC ROYAL Bank")
```

**Comment by nicholasjhenry** [comment]
From our discussion:

```elixir
Ach.DSL.new do 
  header do
    immediate_destination "b071000505",
    immediate_destination_name "RBC ROYAL Bank",
    immediate_origin "0123456789",
    immediate_origin_name "ORIGIN Bank"
  end
  
  batch do
    
  end
end

describe "constructing a header" do
with {:ok, account_number} <- AccountNumber.new("123232"),
     {:ok, origin_name} <- AccountName.new("10.00"),
    {:ok, header} <- Ach.Header.new(
      account_number,
      immediate_origin_name: origin_name
      ),
      {:ok, record} = Ach.Record.new(header, batches),
      do: Ach.Record.to_string(record)
    end
 

Ach.Builder.new
|> Ach.Builder.put_header!(header)
|> Ach.Builder.put_batch!(batch_1)
|> Ach.Builder.put_batch!(batch_2)
|> Ach.Builder.build

Ach.Record.new(header, batches)
|> Ach.Record.to_string
```

**Comment by nicocharlery** [comment]
We will merge the two pending request in order to start the refactoring based on our discussion.

**Pull request merged**
